name: Build Astro

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  pull_request:
    branches:
    - main

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2.0.0
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
          package-manager: pnpm@latest
